<?php

use App\Jobs\ProvisionJuicyWayWalletJob;
// Deploy to: config/services.php

return [

    'postmark' => [
        'token' => env('POSTMARK_TOKEN'),
    ],

    'ses' => [
        'key'    => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    ],

    'resend' => [
        'key' => env('RESEND_KEY'),
    ],

    'slack' => [
        'notifications' => [
            'bot_user_oauth_token' => env('SLACK_BOT_USER_OAUTH_TOKEN'),
            'channel'              => env('SLACK_BOT_USER_DEFAULT_CHANNEL'),
        ],
    ],

    'paystack' => [
        'public_key' => env('PAYSTACK_PUBLIC_KEY'),
        'secret_key' => env('PAYSTACK_SECRET_KEY'),
    ],

    'monnify' => [
        'api_key'       => env('MONNIFY_API_KEY'),
        'secret_key'    => env('MONNIFY_SECRET_KEY'),
        'contract_code' => env('MONNIFY_CONTRACT_CODE'),
        'base_url'      => env('MONNIFY_BASE_URL', 'https://sandbox.monnify.com'),
    ],

    // ── JuicyWay ─────────────────────────────────────────────────────────────
    // Used for payment link creation and inbound webhook checksum verification.
    // Credentials are provided by PayGrid (they manage the JuicyWay account).
    // NEVER commit these values to git.
    'juicyway' => [
        'api_key'     => env('JUICYWAY_API_KEY'),
        'business_id' => env('JUICYWAY_BUSINESS_ID'),   // used for checksum verification ONLY
        'base_url'    => env('JUICYWAY_API_BASE_URL', 'https://api.spendjuice.com'),
    ],

    // ── PayGrid ──────────────────────────────────────────────────────────────
    // PayGrid fires a signed webhook to SchoolMS when a parent's bank transfer
    // is detected and posted to Nurtureville's ledger.
    // Set PAYGRID_WEBHOOK_SECRET in .env — generated by PayGrid when
    // configuring the outbound webhook for Nurtureville's organisation.
    'paygrid' => [
        'webhook_secret' => env('PAYGRID_WEBHOOK_SECRET', ''),
        // API key for posting inflows to Nurtureville's PayGrid ledger.
        // Generated by PayGrid admin for Nurtureville's organisation.
        // Set PAYGRID_API_KEY and PAYGRID_API_BASE_URL in .env.
        'api_key'      => env('PAYGRID_API_KEY', ''),
        'api_base_url' => env('PAYGRID_API_BASE_URL', ''),
        // Raw BudPay webhook forward — SchoolMS posts to this URL after processing
        'webhook_url'  => env('PAYGRID_WEBHOOK_URL', ''),
    ],

    'budpay' => [
        'secret_key' => env('BUDPAY_SECRET_KEY'),
        'public_key' => env('BUDPAY_PUBLIC_KEY'),
        'base_url'   => env('BUDPAY_BASE_URL', 'https://api.budpay.com/api/v2'),
    ],

    'korapay' => [
        'secret_key' => env('KORAPAY_SECRET_KEY'),
        'public_key' => env('KORAPAY_PUBLIC_KEY'),
        'base_url'   => env('KORAPAY_BASE_URL', 'https://api.korapay.com/merchant/api/v1'),
        'bank_code'  => env('KORAPAY_BANK_CODE', '035'),
        'bvn'        => env('KORAPAY_BVN'),
    ],

    // ── Wallet Provider Configuration ────────────────────────────────────────
    // Determines which payment provider is used for virtual account provisioning.
    // Priority:
    //   1. Admin override in school_settings (wallet_provider)
    //   2. WALLET_PROVIDER in .env
    //   3. Default fallback (budpay)
    //
    // Supported values: 'budpay', 'juicyway'
    'wallet' => [
        'default' => env('WALLET_PROVIDER', 'budpay'),
        'providers' => [
            'budpay' => [
                'name' => 'BudPay',
                'job' => \App\Jobs\ProvisionParentWalletJob::class,
            ],
            'juicyway' => [
                'name' => 'JuicyWay',
                'job' => ProvisionJuicyWayWalletJob::class,
            ],
        ],
    ],

];
